name: time_track
description: "Application de suivi du temps multi-plateforme."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Style
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  intl: ^0.20.2
  flutter_blurhash: ^0.9.1

  # State Management
  flutter_riverpod: ^2.6.1

  # Data — SQLite (Drift)
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  path: ^1.9.0               # <--- AJOUTÉ : Pour p.join dans database.dart
  sqlite3_flutter_libs: ^0.5.25 # <--- AJOUTÉ : Indispensable pour macOS/iOS/Android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Générateurs Drift
  drift_dev: ^2.23.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true # Nécessaire pour l'internationalisation (.arb)

  # Assure-toi que ces dossiers existent !
  assets:
    - assets/fonts/
    # - assets/images/ # Si tu as des logos ou icônes

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf
        - asset: assets/fonts/Inter-Italic-Variable.ttf